language: java

default_analysis:
  open_source: true
  commands:
    - mvn test
 
coverage:
  precision: 2
  round: down
  range: "50..80"
  
ignore:
  - '**/src/test/**/*'
  - '**/target/**/*'
 
features:
  delete_reports: true
