version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
      
    steps:
      # Checkout the code as the first step.
      - checkout

      # Use mvn clean and package as the standard maven build phase
      - run:
          name: Build
          command: mvn clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
      - run:   
           name: Upload coverage reports to Codecov
           uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: Chris2018998/BeeOP

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
